### ISSUE TITLE
Error: 'SuiRpcResult' object has no attribute 'next_cursor'

### ISSUE THREAD

**Issue by RandyPen** [FrankC01/pysui#200]
I run example code `pgql_s_example.py` and `pgql_a_example.py`, there is one same bug.
```
Traceback (most recent call last):
  File "/Users/xxx/Code/suiview/pgql_s_example.py", line 629, in <module>
    do_all_balances(client_init)
  File "/Users/xxx/Code/suiview/pgql_s_example.py", line 127, in do_all_balances
    next_page=result.next_cursor,
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'SuiRpcResult' object has no attribute 'next_cursor'
```

**Comment by FrankC01** [comment]
What version of pysui are you running with.

**Comment by FrankC01** [comment]
Pushed fix to the same files, nice catch.
